### ISSUE TITLE
Question: How to iterate over properties?

### ISSUE THREAD

**Issue by mictian** [Rapid-Application-Development-JS/gulp-incremental#2]
Hi Team,

First of all, awesome project :+1: 

I'm evaluating gulp-incremental, which so far seems excellent, and I cannot figure out how to evaluate code in properties. My template is the following:

``` javascript
<div class="<% _.each(classes, function (cls) {  %> cls <% } ) %>">
    Content
</div>
```

and the returned value is:

``` javascript
function template(data){
    elementOpen('div', null, null, 'class', '<evaluate>_.each(classes, function (cls) {</evaluate> cls <evaluate>} )</evaluate>');
        text('Content');
    elementClose('div');
}
```

Could you please point me out, how I should achieve this?

BTW: To generate this template I use the code is in your readme:

``` javascript
var gulp = require('gulp');
var concat = require('gulp-concat');
var toIDOM = require('gulp-incremental');

gulp.task('default', function() {
    gulp.src(['*/*.ejs'])
        .pipe(toIDOM())
        .pipe(concat('templates.js'))
        .pipe(gulp.dest('bin/'));
});
```

Thanks in advance.

**Comment by MobiDevBiz** [comment]
Greetings!
Thank you for your attention to our project.

In your case the problem is that you need to assign a value to the properties, while you try to indicate the code from evaluation, and it gets converted incorrectly, as you rightly noted.

There is a quick solution: create a temporary variable, then assign its value to the `class` attribute.

Here is how you can do it:

``` ejs
<%
var classes = '';
data.classes.forEach(function (cls) {classes += cls + ' ';});
%>
<div class="<%=classes.trim()%>">
    Content
</div>
```

in this case, the returned value is:

``` javascript
function template(data){
    var classes = ''; data.classes.forEach(function (cls) {classes += cls + ' ';}); 
    elementOpen('div', null, null, 'class', classes.trim());
        text('Content');
    elementClose('div');
}
```

P.S. Currently we are planning to render gulp-incremental into the code of a [new library](https://github.com/Rapid-Application-Development-JS/itemplate) that can compile templates on the browser side as well, in order to centralize the code in one place.
Besides, the library contains available static arrays and helpers, which allows to use the capabilities of incremental-DOM with more flexibility.

Thank you for your remark about this issue – we'll think of a way to implement your suggestion.

**Comment by mictian** [comment]
Thank you for your answer!

I will apply your fix.
Not just it works but also makes more clear the separation between the HTML and the JS code.
